### ISSUE TITLE
Add support for U-turns

### ISSUE THREAD

**Issue by milkboy** [milkboy/WME-ja#29]
Parallell (±?°) roads with x (<15?) meters in between can cause a "make a U-turn" prompt

**Comment by FZ69617** [comment]
I don't get it. If distance between the two parallel (±5°) roads at the junction is less than 5m, then a U-turn is disallowed - see [U-turn avoidance conditions in Wiki](https://wiki.waze.com/wiki/Junction_Style_Guide/Intersections#Avoiding_U_turns_in_box_and_partial_box_intersections).
In fact, I've never heard a "take a U-turn" instruction on the junctions with a U-turn allowed in between an entry and exit segments connected with a short segment - e.g. [between this two segments](https://www.waze.com/editor/?env=row&lon=15.49061&lat=51.93497&layers=1476&zoom=8&segments=256328574,259019704) two "turn left" instructions are emitted by Waze, instead of an effective "U-turn".
AFAIK, the U-turn instructions are currently emitted only for a single, two-way roads at the junctions, or at ends of the roads (of course, only if allowed by a green U-turn arrow).

Nevertheless, I think it would be useful to show an angle between the two selected segments connected with another (short?) segment. And, in addition to the angle, tell the user whether a U-turn is allowed or not between these two selected segments. What do you think?

**Comment by wlodek76** [comment]
Interesting Idea!
To show U-turn on the WME instead of thinking does it generates or not ;)
Many editors even advanced still have troubles with it!

Some tricky example where U-turn works and it was forced :)
https://www.waze.com/pl/editor/?env=row&lon=19.55355&lat=51.75735&layers=388&zoom=10&segments=119190011
![image](https://cloud.githubusercontent.com/assets/7284315/7219159/fa0400ba-e692-11e4-9d35-d7f81d7eafad.png)


It could be nice to estimate U-turn in JAI :)
Examine two parallel selected segments and displaying U-Turn icon or a just simple marker with a word U-Turn.

**Comment by milkboy** [comment]
As long as people don't expect a "u-turn" guidance ;) Forcing this way makes the routing into two separate "turn lefts"

**Comment by FZ69617** [comment]
@milkboy could you please reopen this issue? I have almost finished support for this on my desk. :)
