### ISSUE TITLE
Need gray area angle expansion

### ISSUE THREAD

**Issue by qwaletee** [milkboy/WME-ja#59]
Angle of 45.61 has inconsistent results for continuation or turn.

Example location, Morningstar Rd and Richmond Terrace in Staten Island, NY

Livemap demonstrates a continuation in one direction (because there are no other wide angles): https://www.waze.com/livemap?lon=-74.1431&lat=40.63875&zoom=17&from_lat=40.6369&from_lon=-74.14545&to_lat=40.63874&to_lon=-74.1431

And a keep in the opposite direction (because there are two wide angle continuations): https://www.waze.com/livemap?lon=-74.14412&lat=40.63827&zoom=17&from_lat=40.63874&from_lon=-74.1431&to_lat=40.6369&to_lon=-74.14545

However, JAI has turn for both directions: https://www.waze.com/editor/?env=usa&lon=-74.14441&lat=40.63707&zoom=5&segments=76525744,34068648&mapUpdateRequest=4439054

The UR above claims Waze said to go straight (well, not technically possible, I guess he means he got no instruction). This is consistent with the first link above.

JAI currently has a cutoff is between 45.52 (still ambiguous) and 45.54 (clear turn), don't know which way 4.53 swings. The example above is 45.61, so at the very least, unless we treat this example as an unrepeatable incident, we have to raise the ambiguous range ("not recommended") to at least 45.61. I would recommend 46.5.

**Comment by FZ69617** [comment]
@qwaletee, thanks for the report.

We could of course easily extend a gray zone angle, but in my opinion we already have it too large. An angle is currently 1° wide (0.5° for each side) - quite huge range of angles for which JAI has no clear answer. :/

I suppose, that the root of the problem is in the angle calculation which JAI is currently performing based on the segments' pure geometry.
We don't know the details of the angle computation algorithm used by Waze, but maybe there is a geodesic angle between segments (i.e. an angle between on earth projections of the segments) in use, instead of a pure geometry based approach?
I think, we have to verify this first...

**Comment by milkboy** [comment]
Yeah, without actual knowledge of how the system works, it's quite hard to just "guess" and have it work correctly in all situations. Slightly related issue #74
